CREATE DATABASE CHAT_DB

GO

USE CHAT_DB

GO

CREATE TABLE ACCOUNT(
	ID VARCHAR(24) PRIMARY KEY,
	PWD VARCHAR(24) NOT NULL,
	FULLNAME VARCHAR(64) NOT NULL,
	isONLINE CHAR(1) NOT NULL,
)

GO

CREATE TABLE FILEDOWNLOAD(
	ID INT IDENTITY(1,1) NOT NULL,
	NAMEOFFILE VARCHAR(1024) NOT NULL,
	SENDER VARCHAR(24) NOT NULL,
	RECIEVER VARCHAR(24) NOT NULL,
	PATHOFFILE VARCHAR(1024) NOT NULL
)